os: unstable
cache:
  - node_modules
environment:
  GH_TOKEN:
      secure: OnTqF98RecRT7q6J9WVXhbqJG0kLis8FAiyA4y6BoxQHvPHbt43mEXifx3kPQ5ly
  matrix:
    - nodejs_version: 9
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run dist
artifacts:
- path: dist\*
deploy:
  release: certproof-win-latest-$(APPVEYOR_REPO_COMMIT)
  description: 'CertProof windows latest $(APPVEYOR_REPO_COMMIT) release'
  provider: GitHub
  auth_token:
    secure: OnTqF98RecRT7q6J9WVXhbqJG0kLis8FAiyA4y6BoxQHvPHbt43mEXifx3kPQ5ly
  artifact:
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master

